use_frameworks!

platform :ios, '10.0'

target 'test_pod_foundation_Example' do
  pod 'test_pod_foundation', :path => '../'

  target 'test_pod_foundation_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
